# Generated by Django 4.2.9 on 2024-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='film_title',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
