# Generated by Django 4.2.9 on 2024-01-24 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_review_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='film_title',
        ),
        migrations.AddField(
            model_name='review',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.film'),
        ),
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
