# Generated by Django 4.2.9 on 2024-01-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_review_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='year',
        ),
    ]
