# Generated by Django 4.2.9 on 2024-01-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_review_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Tagline'),
        ),
    ]
