# Generated by Django 4.2.9 on 2024-01-29 12:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_review_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
