# Generated by Django 4.2.9 on 2024-02-02 11:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='film',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(
                blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
